export const carsData = [
  {
    id: 1,
    carBrand: "Audi",
    carModel: "A6",
    year: 2014,
    price: 90,
    seats: 4,
    transmision: "automatic",
    seller: 599001122,
    city: "Tbilisi",
    fuel: 90,
    img: ""
  },
  {
    id: 1,
    carBrand: "Audi",
    carModel: "A6",
    year: 2014,
    price: 90,
    seats: 4,
    transmision: "automatic",
    seller: 599001122,
    city: "Tbilisi",
    fuel: 90,
    img: ""
  },
  {
    id: 1,
    carBrand: "Audi",
    carModel: "A6",
    year: 2014,
    price: 90,
    seats: 4,
    transmision: "automatic",
    seller: 599001122,
    city: "Tbilisi",
    fuel: 90,
    img: ""
  },
  {
    id: 1,
    carBrand: "Audi",
    carModel: "A6",
    year: 2014,
    price: 90,
    seats: 4,
    transmision: "automatic",
    seller: 599001122,
    city: "Tbilisi",
    fuel: 90,
    img: ""
  },
  {
    id: 1,
    carBrand: "Audi",
    carModel: "A6",
    year: 2014,
    price: 90,
    seats: 4,
    transmision: "automatic",
    seller: 599001122,
    city: "Tbilisi",
    fuel: 90,
    img: ""
  },
  {
    id: 1,
    carBrand: "Audi",
    carModel: "A6",
    year: 2014,
    price: 90,
    seats: 4,
    transmision: "automatic",
    seller: 599001122,
    city: "Tbilisi",
    fuel: 90,
    img: ""
  },
  {
    id: 1,
    carBrand: "Audi",
    carModel: "A6",
    year: 2014,
    price: 90,
    seats: 4,
    transmision: "automatic",
    seller: 599001122,
    city: "Tbilisi",
    fuel: 90,
    img: ""
  },
  {
    id: 1,
    carBrand: "Audi",
    carModel: "A6",
    year: 2014,
    price: 90,
    seats: 4,
    transmision: "automatic",
    seller: 599001122,
    city: "Tbilisi",
    fuel: 90,
    img: ""
  },
  {
    id: 1,
    carBrand: "Audi",
    carModel: "A6",
    year: 2014,
    price: 90,
    seats: 4,
    transmision: "automatic",
    seller: 599001122,
    city: "Tbilisi",
    fuel: 90,
    img: ""
  },
];
